import { v4 as uuidv4 } from 'uuid';

export const memeDb = [
  {
    id: uuidv4(),
    title: 'Rest',
    upvotes: 6,
    downvotes: 0,
    img: 'https://i.postimg.cc/jqzFnM1H/9fFD7Sh.jpg',
    starred: false,
  },
  {
    id: uuidv4(),
    title: 'killem all',
    upvotes: 1,
    downvotes: 6,
    img: 'https://i.postimg.cc/kGFYr5S1/AySFpJC.jpg',
    starred: false,
  },
  {
    id: uuidv4(),
    title: 'extra hell',
    upvotes: 10,
    downvotes: 3,
    img: 'https://i.postimg.cc/SxKT5kxd/K618E0X.jpg',
    starred: false,
  },
  {
    id: uuidv4(),
    title: 'Space Cat',
    upvotes: 0,
    downvotes: 0,
    img: 'https://i.imgur.com/IZvHqDW.jpeg',
    starred: false,
  },
  {
    id: uuidv4(),
    title: "Dog's mess",
    upvotes: 0,
    downvotes: 0,
    img: 'https://i.imgur.com/CjZgiwh.jpeg',
    starred: false,
  },
  {
    id: uuidv4(),
    title: 'zebra',
    upvotes: 0,
    downvotes: 0,
    img: 'https://i.postimg.cc/QxhnQpLR/mU6rAFB.jpg',
    starred: false,
  },
  {
    id: uuidv4(),
    title: 'broken egg',
    upvotes: 1,
    downvotes: 0,
    img: 'https://i.postimg.cc/hPsZpfch/7h08Otr.jpg',
    starred: false,
  },
];
